parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - wantora
  - wantora-react

env:
  es6: true
  browser: true
  commonjs: true

globals:
  process: false

overrides:
  - files:
      - webpack.config.js
      - scripts/**/*.js
    parserOptions:
      sourceType: script
    env:
      browser: false
      node: true
